config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#new'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :articles
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :recent, -> { reorder(created_at: :desc) }
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  is_impressionable
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  validates :content, presence: true, length: { maximum: 140 }

  delegate :name, to: :author, prefix: true, allow_nil: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_secure_password

  has_many :articles, -> { includes(:author) }, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }
  validates :password, presence: true, length: { minimum: 6, maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: URI::MailTo::EMAIL_REGEXP },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :logged_in_user

  include SessionsHelper

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  impressionist actions: [:show], unique: %i[impressionable_type impressionable_id session_hash]

  def index
    @q = current_articles.recent.search(params[:q])
    @articles = @q.result.paginate(page: params[:page], per_page: 10)
  end

  def show; end

  def new
    @article = current_user.articles.new
  end

  def edit; end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      flash[:success] = 'Article was successfully created.'
      redirect_to @article
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated.'
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:success] = 'Article was successfully destroyed.'
    redirect_to articles_url
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :published, :published_at)
  end

  def current_articles
    current_user&.admin ? Article : current_user.articles
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :logged_in_user

  def new; end

  def create
    user = User.find_by(email: params.dig(:session, :email).downcase)
    if user&.authenticate(params.dig(:session, :password))
      log_in user
      redirect_back_or(articles_url)
    else
      flash.now[:danger] = 'Invalid email/password combination. Please check it again'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :logged_in_user, only: %i[new create]

  before_action :find_user, only: :show
  def new
    @user = User.new
  end

  def show; end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to Ekohe! Nice to meet you!'
      redirect_to @user
    else
      render :new
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # store original url
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :title, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :title, class: "form-control-plaintext form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :content, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :content, class: "form-control-plaintext form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :published, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.check_box :published, class: "form-control-plaintext" %>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :published_at, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <div class="form-group">
        <div class='input-group date' id='datetimepicker'>
          <%= form.text_field :published_at, class: "form-control" %>
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-time"></span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-12">
      <%= form.submit "Save", class: "btn btn-xs btn-primary" %>
      <%= link_to 'Back', articles_path, class: "btn btn-xs btn-primary" %>
    </div>
  </div>
<% end %>
<script type="text/javascript">
$(function () {
  $('#datetimepicker').datetimepicker({
    viewMode: 'years',
    format: 'YYYY-MM-DD'
  });
});
</script>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<% if @articles.total_entries.zero? %>
  <h1>More interesting in <%= link_to "Ekohe!", "https://ekohe.com/", target: :_blank %></h1>
  <%= link_to 'New a article. Have fun.^_^', new_article_path, class: 'btn btn-xs btn-primary pull-left' %>
<% else %>
  <h1><%= pluralize(@articles.total_entries, "Article") %></h1>
<%= search_form_for @q, class: "form-inline" do |f| %>
    <div class="row pull-right">
      <form class="form-search">
        <%= f.label :title %>:
        <%= f.search_field :title_cont, class: "nput-medium search-query" %>
        <%= f.submit class: "btn btn-xs btn-info" %>
      </form>
    </div>
  <% end %>
  <%= link_to 'New Article', new_article_path, class: 'btn btn-xs btn-primary pull-left' %>
  <br>
  <br>
  <table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
      <tr>
        <th>Title</th>
        <th>View Count</th>
        <th style="width:30%">Content</th>
        <th>Author</th>
        <th>Published</th>
        <th>Published at</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each_with_index do |article, index| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.impressionist_count %></td>
          <td>
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse_<%= index %>">
              <%= article.content.truncate_words(4) %>
            </a>
            <div id="collapse_<%= index %>" class="accordion-body collapse">
              <div class="accordion-inner">
                <%= article.content %>
              </div>
            </div>
          </td>
          <td><%= article.author_name %></td>
          <td><%= article.published %></td>
          <td><%= article.published_at %></td>
          <td><%= link_to 'Show', article, class: 'btn btn-xs btn-info' %> <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-xs btn-info' %> <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-info' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="card text-left border-primary" style="width: 50rem;">
  <div class="card-header text-primary">
    <h4 class="card-title"><%= @article.title %></h4>
  </div>
  <div class="card-body">
    <h5 class="card-subtitle mb-2">
      <span class="text-muted"> <%= time_ago_in_words(@article.created_at) %> ago by </span>
      <span class="text-info"><%= @article.author_name %></span>
    </h5>
    <span class="text-warning"><%= pluralize(@article.impressionist_count, "view") %> so far!</span>
    <p class="card-text text-primary"><%= @article.content %></p>
  </div>
  <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-xs btn-primary" %>
  <%= link_to 'Back', articles_path, class: "btn btn-xs btn-primary" %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <li><%= link_to current_user.email, "#" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EkoheBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title><%= yield :title || "Ekohe" %></title>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<%= provide :title, "Sign up" %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Hello <%= @user.name %>, welcome to <%= link_to "Ekohe!", "https://ekohe.com/", target: :_blank %></h1>
<%= link_to "Go surfing", articles_path, class: "btn btn-primary" %>